language: node_js
node_js:
- node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: q2pxmlc3Ly8C2Ws+q51w2CTYFMYUrEzOVBUsfIyNTN3qxLmZeTqDa6Wbmbcmok4w6cZUkZz5DE79FlEOuGGouWjtcQbR52HWOgioR3XQtAdXmrNcj8l6opQq1kftIkA+CDUDIH6uXfi2ndejZ6qAhJytBQeaf7vgVAKf0T5/6xCP8Mm5ogQpsfheP9WKbV55v1BF+Ab4XlyyrXM4/i8xz8wMofYBoLnJeZWrz/ZzfX5wj68HgFJ9UOD1A19UHgQnvaJR5/XvShW9nOjB6KCKaXCITdq0GFW5quQ5Vq5iZksdPVtOi/chXT4lMyE2E85zfF3P91Z+RZSYnLH73WOrcmf8qdysq2l4W+Uqhn5xWTH017VdebMe4c4RDyMDmbOZgmkpFjw94ktclb+4fCZEgeMgOWv4aMyXnRaoeWQDfxH8aczwWtpwqZupcmTSkCYYekpwM8N92AIoKhIipb6lKhCZWIKfTPwvRww1il11sO+kGO4YRLrYCCa02iqUM4AB8FkiNffNveNW5ICDAuzLYWwXvECoPK41CillNRs8JZFZYOiSa6In+GVAHr2W4yNcHdQ3NJw6et0jaIMm9XZn6FFHlXLEA90ojVXsscB3//Sm04LXCatH3oMFNtGM7Odlx5xJLYRRx5wto7pRokSIJfOUcj0Xi47jbiJFmoCAJDo=
  app: obscure-eyrie-94072
  on:
    repo: leesander1/hearmenow-server
    branch: master
notifications:
  email:
  - lee@leesander.com
