language: node_js
node_js:
  - "node"

services:
  - mongodb
  
deploy:
  provider: heroku
  api_key:
    app: obscure-eyrie-94072

notifications:
  email:
    - lee@leesander.com

services:
  - mongodb
